### ISSUE TITLE
Depends on outdated lru

### ISSUE THREAD

**Issue by RalfJung** [FauxFaux/sortuniq#1]
This crate depends on an old buggy version of lru, which with some planned compiler changes (https://github.com/rust-lang/rust/pull/71274) might stop working in the future. lru has been updated since then, would be great if you could bump your dependencies. :)

**Comment by FauxFaux** [comment]
Thanks!

I'm going to deprecate (or yank?) this crate and repo, as it's almost merged into https://github.com/FauxFaux/muchutils#sortuniq .

**Comment by FauxFaux** [comment]
Wow, what an outdated comment. What even is that other repo?!

Fixed, anyway.
